#!/usr/bin/env python
# vim:et:sta:sts=4:sw=4:ts=8:tw=79:

import gtk
import sys

# Internationalization
import locale
import gettext
locale.setlocale(locale.LC_ALL, '')
locale.bindtextdomain("salix-update-notifier", "/usr/share/locale")
gettext.bindtextdomain("salix-update-notifier", "/usr/share/locale")
gettext.textdomain("salix-update-notifier")
_ = gettext.gettext

def close_app(data=None):
    sys.exit(1)

def make_menu(event_button, event_time, data=None):
    menu = gtk.Menu()
    close_item = gtk.ImageMenuItem(gtk.STOCK_CLOSE)

    #Append the menu items    
    menu.append(close_item)
    #add callbacks
    close_item.connect_object("activate", close_app, "Exit")
    #Show the menu items
    close_item.show()
    #Popup the menu
    menu.popup(None, None, None, event_button, event_time)

def on_right_click(data, event_button, event_time):
    make_menu(event_button, event_time)

def on_left_click(event):
    sys.exit(0)

if __name__ == '__main__':
    icon = gtk.status_icon_new_from_icon_name("salix-update-notifier")
    icon.set_tooltip_text(_('Package updates are available.'))
    icon.connect('popup-menu', on_right_click)
    icon.connect('activate', on_left_click)
    gtk.main()
